version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/build-changelog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/package-version"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/pull-request"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/slack-message"
    schedule:
      interval: "weekly"
